# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    set_event_details_params as set_event_details_params,
)

get_events_from_combined_params = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events_from_combined_params",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.config import (
    default_if_string_is_empty as default_if_string_is_empty,
)
from ecoscope_workflows_core.tasks.config import title_case_var as title_case_var
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_is_none as any_dependency_is_none,
)
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import assign_value as assign_value
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_core.tasks.transformation import (
    title_case_columns_by_prefix as title_case_columns_by_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_analysis_field_from_event_details as get_analysis_field_from_event_details,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_analysis_field_label_from_event_details as get_analysis_field_label_from_event_details,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_analysis_field_unit_from_event_details as get_analysis_field_unit_from_event_details,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_category_field_from_event_details as get_category_field_from_event_details,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_category_field_label_from_event_details as get_category_field_label_from_event_details,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_event_type_from_event_details as get_event_type_from_event_details,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

get_choices_from_v2_event_type = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_choices_from_v2_event_type",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import (
    concat_string_vars as concat_string_vars,
)
from ecoscope_workflows_core.tasks.config import (
    get_column_names_from_dataframe as get_column_names_from_dataframe,
)
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_is_empty_string as any_dependency_is_empty_string,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_column_values_to_numeric as convert_column_values_to_numeric,
)
from ecoscope_workflows_core.tasks.transformation import fill_na as fill_na
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import map_values as map_values
from ecoscope_workflows_core.tasks.transformation import (
    reorder_columns as reorder_columns,
)
from ecoscope_workflows_core.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_core.tasks.transformation import transpose as transpose
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_feature_density as calculate_feature_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    create_meshgrid as create_meshgrid,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polygon_layer as create_polygon_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_pie_chart as draw_pie_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    drop_nan_values_by_column as drop_nan_values_by_column,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_numeric_column as normalize_numeric_column,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client_name": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "set_event_details_combined": ["er_client_name", "time_range"],
        "get_events_data": ["set_event_details_combined"],
        "convert_to_user_timezone": ["get_events_data", "get_timezone"],
        "extract_latitude": ["convert_to_user_timezone"],
        "extract_longitude": ["extract_latitude"],
        "extract_reported_by": ["extract_longitude"],
        "groupers": [],
        "filter_events": ["extract_reported_by"],
        "normalize_event_details": ["filter_events"],
        "events_add_temporal_index": ["normalize_event_details", "groupers"],
        "analysis_field_from_config": ["set_event_details_combined"],
        "analysis_field": ["analysis_field_from_config"],
        "analysis_field_label": ["set_event_details_combined"],
        "analysis_field_unit": ["set_event_details_combined"],
        "category_field_from_config": ["set_event_details_combined"],
        "category_field": ["category_field_from_config"],
        "category_field_label": ["set_event_details_combined"],
        "event_type": ["set_event_details_combined"],
        "add_default_category_column": [
            "events_add_temporal_index",
            "analysis_field_unit",
        ],
        "default_category_field": ["category_field"],
        "category_field_label_or_category": ["category_field_label", "category_field"],
        "default_category_field_label": [
            "category_field_label_or_category",
            "category_field",
        ],
        "title_case_columns": ["add_default_category_column"],
        "get_category_display_names": [
            "er_client_name",
            "event_type",
            "category_field_from_config",
        ],
        "ensure_analysis_column": ["title_case_columns", "analysis_field"],
        "ensure_category_column": ["ensure_analysis_column", "default_category_field"],
        "map_display_names": [
            "ensure_category_column",
            "default_category_field",
            "get_category_display_names",
        ],
        "convert_na_values": ["map_display_names", "default_category_field"],
        "rename_columns": ["convert_na_values"],
        "column_display_order": ["rename_columns"],
        "ensure_numeric": ["rename_columns", "analysis_field"],
        "events_colormap": ["ensure_numeric", "default_category_field"],
        "set_summary_table_title": ["analysis_field_label"],
        "by_category_field_str": ["category_field_label"],
        "pie_chart_title_pt1": ["analysis_field_label"],
        "set_pie_chart_title": ["pie_chart_title_pt1", "by_category_field_str"],
        "set_events_map_title": ["analysis_field_label", "by_category_field_str"],
        "set_bar_chart_title": ["analysis_field_label", "by_category_field_str"],
        "set_density_map_title": ["analysis_field_label"],
        "set_events_table_title": [],
        "split_event_groups": ["events_colormap", "groupers"],
        "drop_nan_values": ["analysis_field", "split_event_groups"],
        "base_map_defs": [],
        "total_events": ["split_event_groups"],
        "total_events_sv_widget": ["total_events"],
        "total_events_grouped_sv_widget": ["total_events_sv_widget"],
        "grouped_event_summary": [
            "analysis_field",
            "analysis_field",
            "analysis_field",
            "analysis_field",
            "analysis_field",
            "drop_nan_values",
        ],
        "transpose_table": ["grouped_event_summary"],
        "rename_summary_columns": ["transpose_table"],
        "summary_table": ["set_summary_table_title", "rename_summary_columns"],
        "summary_html_urls": ["summary_table"],
        "summary_table_single_views": ["set_summary_table_title", "summary_html_urls"],
        "grouped_summary_table_widget": ["summary_table_single_views"],
        "grouped_events_pie_chart": [
            "analysis_field",
            "default_category_field",
            "set_pie_chart_title",
            "drop_nan_values",
        ],
        "grouped_pie_chart_html_urls": ["grouped_events_pie_chart"],
        "grouped_events_pie_chart_widgets": [
            "set_pie_chart_title",
            "grouped_pie_chart_html_urls",
        ],
        "grouped_events_pie_widget_merge": ["grouped_events_pie_chart_widgets"],
        "normalize_analysis_field": ["analysis_field", "split_event_groups"],
        "grouped_events_map_layer": [
            "default_category_field",
            "analysis_field",
            "normalize_analysis_field",
        ],
        "grouped_events_ecomap": [
            "base_map_defs",
            "default_category_field_label",
            "set_events_map_title",
            "grouped_events_map_layer",
        ],
        "grouped_events_ecomap_html_url": ["grouped_events_ecomap"],
        "grouped_events_map_widget": [
            "set_events_map_title",
            "grouped_events_ecomap_html_url",
        ],
        "grouped_events_map_widget_merge": ["grouped_events_map_widget"],
        "events_bar_chart": [
            "analysis_field",
            "default_category_field",
            "set_bar_chart_title",
            "drop_nan_values",
        ],
        "events_bar_chart_html_url": ["events_bar_chart"],
        "events_bar_chart_widget": ["set_bar_chart_title", "events_bar_chart_html_url"],
        "grouped_bar_plot_widget_merge": ["events_bar_chart_widget"],
        "events_meshgrid": ["events_add_temporal_index"],
        "grouped_events_feature_density": [
            "events_meshgrid",
            "analysis_field",
            "split_event_groups",
        ],
        "drop_nan_percentiles": ["grouped_events_feature_density"],
        "sort_grouped_density_values": ["drop_nan_percentiles"],
        "classify_fd": ["sort_grouped_density_values"],
        "grouped_fd_colormap": ["classify_fd"],
        "fd_rename_columns": ["grouped_fd_colormap"],
        "grouped_fd_map_layer": ["fd_rename_columns"],
        "grouped_fd_ecomap": [
            "base_map_defs",
            "analysis_field_unit",
            "set_density_map_title",
            "grouped_fd_map_layer",
        ],
        "grouped_fd_ecomap_html_url": ["grouped_fd_ecomap"],
        "grouped_fd_map_widget": [
            "set_density_map_title",
            "grouped_fd_ecomap_html_url",
        ],
        "grouped_fd_map_widget_merge": ["grouped_fd_map_widget"],
        "events_table_columns": ["column_display_order"],
        "events_table": [
            "events_table_columns",
            "set_events_table_title",
            "split_event_groups",
        ],
        "table_html_urls": ["events_table"],
        "events_table_single_views": ["set_events_table_title", "table_html_urls"],
        "grouped_table_widget": ["events_table_single_views"],
        "events_dashboard": [
            "workflow_details",
            "total_events_grouped_sv_widget",
            "grouped_summary_table_widget",
            "grouped_events_pie_widget_merge",
            "grouped_events_map_widget_merge",
            "grouped_bar_plot_widget_merge",
            "grouped_fd_map_widget_merge",
            "grouped_table_widget",
            "groupers",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "set_event_details_combined": Node(
            async_task=set_event_details_params.validate()
            .set_task_instance_id("set_event_details_combined")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "location",
                    "event_details",
                    "geometry",
                ],
                "raise_on_empty": False,
                "include_details": True,
                "include_updates": False,
                "include_related_events": False,
                "include_display_values": False,
            }
            | (params_dict.get("set_event_details_combined") or {}),
            method="call",
        ),
        "get_events_data": Node(
            async_task=get_events_from_combined_params.validate()
            .set_task_instance_id("get_events_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "convert_to_user_timezone": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_to_user_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_events_data"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_to_user_timezone") or {}),
            method="call",
        ),
        "extract_latitude": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_latitude")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_to_user_timezone"),
                "column_name": "location",
                "field_name_options": [
                    "latitude",
                ],
                "output_type": "str",
                "output_column_name": "latitude",
            }
            | (params_dict.get("extract_latitude") or {}),
            method="call",
        ),
        "extract_longitude": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_longitude")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_latitude"),
                "column_name": "location",
                "field_name_options": [
                    "longitude",
                ],
                "output_type": "str",
                "output_column_name": "longitude",
            }
            | (params_dict.get("extract_longitude") or {}),
            method="call",
        ),
        "extract_reported_by": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_reported_by")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_longitude"),
                "column_name": "reported_by",
                "field_name_options": [
                    "name",
                ],
                "output_type": "str",
                "output_column_name": "reported_by_name",
            }
            | (params_dict.get("extract_reported_by") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "filter_events": Node(
            async_task=apply_reloc_coord_filter.validate()
            .set_task_instance_id("filter_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_reported_by"),
                "roi_gdf": None,
                "roi_name": None,
            }
            | (params_dict.get("filter_events") or {}),
            method="call",
        ),
        "normalize_event_details": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_events"),
                "column": "event_details",
                "skip_if_not_exists": False,
                "sort_columns": False,
            }
            | (params_dict.get("normalize_event_details") or {}),
            method="call",
        ),
        "events_add_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("events_add_temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_event_details"),
                "time_col": "time",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("events_add_temporal_index") or {}),
            method="call",
        ),
        "analysis_field_from_config": Node(
            async_task=get_analysis_field_from_event_details.validate()
            .set_task_instance_id("analysis_field_from_config")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("analysis_field_from_config") or {}),
            method="call",
        ),
        "analysis_field": Node(
            async_task=title_case_var.validate()
            .set_task_instance_id("analysis_field")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": DependsOn("analysis_field_from_config"),
            }
            | (params_dict.get("analysis_field") or {}),
            method="call",
        ),
        "analysis_field_label": Node(
            async_task=get_analysis_field_label_from_event_details.validate()
            .set_task_instance_id("analysis_field_label")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("analysis_field_label") or {}),
            method="call",
        ),
        "analysis_field_unit": Node(
            async_task=get_analysis_field_unit_from_event_details.validate()
            .set_task_instance_id("analysis_field_unit")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("analysis_field_unit") or {}),
            method="call",
        ),
        "category_field_from_config": Node(
            async_task=get_category_field_from_event_details.validate()
            .set_task_instance_id("category_field_from_config")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("category_field_from_config") or {}),
            method="call",
        ),
        "category_field": Node(
            async_task=title_case_var.validate()
            .set_task_instance_id("category_field")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_dependency_is_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": DependsOn("category_field_from_config"),
            }
            | (params_dict.get("category_field") or {}),
            method="call",
        ),
        "category_field_label": Node(
            async_task=get_category_field_label_from_event_details.validate()
            .set_task_instance_id("category_field_label")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_dependency_is_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("category_field_label") or {}),
            method="call",
        ),
        "event_type": Node(
            async_task=get_event_type_from_event_details.validate()
            .set_task_instance_id("event_type")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "combined_params": DependsOn("set_event_details_combined"),
            }
            | (params_dict.get("event_type") or {}),
            method="call",
        ),
        "add_default_category_column": Node(
            async_task=assign_value.validate()
            .set_task_instance_id("add_default_category_column")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_add_temporal_index"),
                "column_name": "default_category",
                "value": DependsOn("analysis_field_unit"),
                "noop_if_column_exists": False,
            }
            | (params_dict.get("add_default_category_column") or {}),
            method="call",
        ),
        "default_category_field": Node(
            async_task=default_if_string_is_empty.validate()
            .set_task_instance_id("default_category_field")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "value": DependsOn("category_field"),
                "default": "default_category",
            }
            | (params_dict.get("default_category_field") or {}),
            method="call",
        ),
        "category_field_label_or_category": Node(
            async_task=default_if_string_is_empty.validate()
            .set_task_instance_id("category_field_label_or_category")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "value": DependsOn("category_field_label"),
                "default": DependsOn("category_field"),
            }
            | (params_dict.get("category_field_label_or_category") or {}),
            method="call",
        ),
        "default_category_field_label": Node(
            async_task=default_if_string_is_empty.validate()
            .set_task_instance_id("default_category_field_label")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "value": DependsOn("category_field_label_or_category"),
                "default": DependsOn("category_field"),
            }
            | (params_dict.get("default_category_field_label") or {}),
            method="call",
        ),
        "title_case_columns": Node(
            async_task=title_case_columns_by_prefix.validate()
            .set_task_instance_id("title_case_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_default_category_column"),
                "prefix": "event_details__",
            }
            | (params_dict.get("title_case_columns") or {}),
            method="call",
        ),
        "get_category_display_names": Node(
            async_task=get_choices_from_v2_event_type.validate()
            .set_task_instance_id("get_category_display_names")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "event_type": DependsOn("event_type"),
                "choice_field": DependsOn("category_field_from_config"),
            }
            | (params_dict.get("get_category_display_names") or {}),
            method="call",
        ),
        "ensure_analysis_column": Node(
            async_task=assign_value.validate()
            .set_task_instance_id("ensure_analysis_column")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("title_case_columns"),
                "column_name": DependsOn("analysis_field"),
                "value": None,
                "noop_if_column_exists": True,
            }
            | (params_dict.get("ensure_analysis_column") or {}),
            method="call",
        ),
        "ensure_category_column": Node(
            async_task=assign_value.validate()
            .set_task_instance_id("ensure_category_column")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("ensure_analysis_column"),
                "column_name": DependsOn("default_category_field"),
                "value": "None",
                "noop_if_column_exists": True,
            }
            | (params_dict.get("ensure_category_column") or {}),
            method="call",
        ),
        "map_display_names": Node(
            async_task=map_values.validate()
            .set_task_instance_id("map_display_names")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("ensure_category_column"),
                "column_name": DependsOn("default_category_field"),
                "value_map": DependsOn("get_category_display_names"),
                "missing_values": "preserve",
                "replacement": None,
            }
            | (params_dict.get("map_display_names") or {}),
            method="call",
        ),
        "convert_na_values": Node(
            async_task=fill_na.validate()
            .set_task_instance_id("convert_na_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_display_names"),
                "value": "None",
                "columns": [
                    DependsOn("default_category_field"),
                ],
            }
            | (params_dict.get("convert_na_values") or {}),
            method="call",
        ),
        "rename_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_na_values"),
                "drop_columns": [
                    "reported_by",
                    "location",
                    "Updates",
                ],
                "rename_columns": {
                    "serial_number": "Serial Number",
                    "time": "Event Time",
                    "reported_by_name": "Reported By",
                    "latitude": "Latitude",
                    "longitude": "Longitude",
                    "event_category": "Event Category",
                },
            }
            | (params_dict.get("rename_columns") or {}),
            method="call",
        ),
        "column_display_order": Node(
            async_task=reorder_columns.validate()
            .set_task_instance_id("column_display_order")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_columns"),
                "columns": [
                    "Serial Number",
                    "Event Time",
                    "Reported By",
                    "Latitude",
                    "Longitude",
                ],
            }
            | (params_dict.get("column_display_order") or {}),
            method="call",
        ),
        "ensure_numeric": Node(
            async_task=convert_column_values_to_numeric.validate()
            .set_task_instance_id("ensure_numeric")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_columns"),
                "columns": [
                    DependsOn("analysis_field"),
                ],
            }
            | (params_dict.get("ensure_numeric") or {}),
            method="call",
        ),
        "events_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("events_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("ensure_numeric"),
                "input_column_name": DependsOn("default_category_field"),
                "colormap": [
                    "#312B86",
                    "#08D1CC",
                    "#FF3FB3",
                    "#20BF55",
                    "#FF9F1C",
                    "#6460B0",
                    "#FF7FCC",
                    "#4DE3DD",
                    "#6BE39A",
                    "#FFC46F",
                    "#1E215C",
                    "#C80088",
                    "#008784",
                    "#08853A",
                    "#C46C00",
                ],
                "output_column_name": "events_colormap",
            }
            | (params_dict.get("events_colormap") or {}),
            method="call",
        ),
        "set_summary_table_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_summary_table_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": DependsOn("analysis_field_label"),
            }
            | (params_dict.get("set_summary_table_title") or {}),
            method="call",
        ),
        "by_category_field_str": Node(
            async_task=concat_string_vars.validate()
            .set_task_instance_id("by_category_field_str")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_dependency_is_empty_string,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "values": [
                    " by ",
                    DependsOn("category_field_label"),
                ],
            }
            | (params_dict.get("by_category_field_str") or {}),
            method="call",
        ),
        "pie_chart_title_pt1": Node(
            async_task=concat_string_vars.validate()
            .set_task_instance_id("pie_chart_title_pt1")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "values": [
                    "Proportion of ",
                    DependsOn("analysis_field_label"),
                ],
            }
            | (params_dict.get("pie_chart_title_pt1") or {}),
            method="call",
        ),
        "set_pie_chart_title": Node(
            async_task=concat_string_vars.validate()
            .set_task_instance_id("set_pie_chart_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "values": [
                    DependsOn("pie_chart_title_pt1"),
                    DependsOn("by_category_field_str"),
                ],
            }
            | (params_dict.get("set_pie_chart_title") or {}),
            method="call",
        ),
        "set_events_map_title": Node(
            async_task=concat_string_vars.validate()
            .set_task_instance_id("set_events_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "values": [
                    DependsOn("analysis_field_label"),
                    DependsOn("by_category_field_str"),
                    " Locations",
                ],
            }
            | (params_dict.get("set_events_map_title") or {}),
            method="call",
        ),
        "set_bar_chart_title": Node(
            async_task=concat_string_vars.validate()
            .set_task_instance_id("set_bar_chart_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "values": [
                    DependsOn("analysis_field_label"),
                    DependsOn("by_category_field_str"),
                    " Over Time",
                ],
            }
            | (params_dict.get("set_bar_chart_title") or {}),
            method="call",
        ),
        "set_density_map_title": Node(
            async_task=concat_string_vars.validate()
            .set_task_instance_id("set_density_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "values": [
                    DependsOn("analysis_field_label"),
                    " Density",
                ],
            }
            | (params_dict.get("set_density_map_title") or {}),
            method="call",
        ),
        "set_events_table_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_events_table_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Events Table",
            }
            | (params_dict.get("set_events_table_title") or {}),
            method="call",
        ),
        "split_event_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_event_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_colormap"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_event_groups") or {}),
            method="call",
        ),
        "drop_nan_values": Node(
            async_task=drop_nan_values_by_column.validate()
            .set_task_instance_id("drop_nan_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": DependsOn("analysis_field"),
            }
            | (params_dict.get("drop_nan_values") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "total_events": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("total_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("total_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "total_events_sv_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_events_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Event Count",
                "decimal_places": 1,
            }
            | (params_dict.get("total_events_sv_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("total_events"),
            },
        ),
        "total_events_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("total_events_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("total_events_sv_widget"),
            }
            | (params_dict.get("total_events_grouped_sv_widget") or {}),
            method="call",
        ),
        "grouped_event_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("grouped_event_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "summary_params": [
                    {
                        "display_name": "Sum",
                        "aggregator": "sum",
                        "column": DependsOn("analysis_field"),
                    },
                    {
                        "display_name": "Min",
                        "aggregator": "min",
                        "column": DependsOn("analysis_field"),
                    },
                    {
                        "display_name": "Max",
                        "aggregator": "max",
                        "column": DependsOn("analysis_field"),
                    },
                    {
                        "display_name": "Median",
                        "aggregator": "median",
                        "column": DependsOn("analysis_field"),
                    },
                    {
                        "display_name": "Mean",
                        "aggregator": "mean",
                        "column": DependsOn("analysis_field"),
                    },
                ],
                "groupby_cols": None,
                "reset_index": False,
            }
            | (params_dict.get("grouped_event_summary") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("drop_nan_values"),
            },
        ),
        "transpose_table": Node(
            async_task=transpose.validate()
            .set_task_instance_id("transpose_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "transposed_column_name": "Summary Stats",
            }
            | (params_dict.get("transpose_table") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_event_summary"),
            },
        ),
        "rename_summary_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_summary_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "0": "Summary Values",
                },
            }
            | (params_dict.get("rename_summary_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("transpose_table"),
            },
        ),
        "summary_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("summary_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "Summary Stats",
                    "Summary Values",
                ],
                "table_config": {
                    "enable_sorting": True,
                    "enable_filtering": False,
                    "enable_download": True,
                    "hide_header": True,
                },
                "widget_id": DependsOn("set_summary_table_title"),
            }
            | (params_dict.get("summary_table") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("rename_summary_columns"),
            },
        ),
        "summary_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("summary_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("summary_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("summary_table"),
            },
        ),
        "summary_table_single_views": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("summary_table_single_views")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_summary_table_title"),
            }
            | (params_dict.get("summary_table_single_views") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("summary_html_urls"),
            },
        ),
        "grouped_summary_table_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_summary_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("summary_table_single_views"),
            }
            | (params_dict.get("grouped_summary_table_widget") or {}),
            method="call",
        ),
        "grouped_events_pie_chart": Node(
            async_task=draw_pie_chart.validate()
            .set_task_instance_id("grouped_events_pie_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "value_column": DependsOn("analysis_field"),
                "color_column": "events_colormap",
                "plot_style": {
                    "textinfo": "value",
                },
                "label_column": DependsOn("default_category_field"),
                "layout_style": None,
                "widget_id": DependsOn("set_pie_chart_title"),
            }
            | (params_dict.get("grouped_events_pie_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("drop_nan_values"),
            },
        ),
        "grouped_pie_chart_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("grouped_pie_chart_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("grouped_pie_chart_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("grouped_events_pie_chart"),
            },
        ),
        "grouped_events_pie_chart_widgets": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("grouped_events_pie_chart_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_pie_chart_title"),
            }
            | (params_dict.get("grouped_events_pie_chart_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("grouped_pie_chart_html_urls"),
            },
        ),
        "grouped_events_pie_widget_merge": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_events_pie_widget_merge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("grouped_events_pie_chart_widgets"),
            }
            | (params_dict.get("grouped_events_pie_widget_merge") or {}),
            method="call",
        ),
        "normalize_analysis_field": Node(
            async_task=normalize_numeric_column.validate()
            .set_task_instance_id("normalize_analysis_field")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": DependsOn("analysis_field"),
                "output_column_name": "normalized_analysis_field",
            }
            | (params_dict.get("normalize_analysis_field") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "grouped_events_map_layer": Node(
            async_task=create_point_layer.validate()
            .set_task_instance_id("grouped_events_map_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "fill_color_column": "events_colormap",
                    "get_radius": "normalized_analysis_field",
                    "stroked": True,
                    "get_line_color": "#FFFFFF",
                    "radius_scale": 5,
                },
                "legend": {
                    "label_column": DependsOn("default_category_field"),
                    "color_column": "events_colormap",
                },
                "tooltip_columns": [
                    "Serial Number",
                    "Event Time",
                    "Reported By",
                    DependsOn("analysis_field"),
                ],
            }
            | (params_dict.get("grouped_events_map_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("normalize_analysis_field"),
            },
        ),
        "grouped_events_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("grouped_events_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": None,
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": DependsOn("default_category_field_label"),
                    "format_title": False,
                    "placement": "bottom-right",
                },
                "static": False,
                "max_zoom": 20,
                "widget_id": DependsOn("set_events_map_title"),
            }
            | (params_dict.get("grouped_events_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("grouped_events_map_layer"),
            },
        ),
        "grouped_events_ecomap_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("grouped_events_ecomap_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("grouped_events_ecomap_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("grouped_events_ecomap"),
            },
        ),
        "grouped_events_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("grouped_events_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_events_map_title"),
            }
            | (params_dict.get("grouped_events_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("grouped_events_ecomap_html_url"),
            },
        ),
        "grouped_events_map_widget_merge": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_events_map_widget_merge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("grouped_events_map_widget"),
            }
            | (params_dict.get("grouped_events_map_widget_merge") or {}),
            method="call",
        ),
        "events_bar_chart": Node(
            async_task=draw_time_series_bar_chart.validate()
            .set_task_instance_id("events_bar_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "x_axis": "Event Time",
                "y_axis": DependsOn("analysis_field"),
                "category": DependsOn("default_category_field"),
                "agg_function": "sum",
                "color_column": "events_colormap",
                "plot_style": {
                    "xperiodalignment": "middle",
                },
                "layout_style": None,
                "widget_id": DependsOn("set_bar_chart_title"),
            }
            | (params_dict.get("events_bar_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("drop_nan_values"),
            },
        ),
        "events_bar_chart_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("events_bar_chart_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("events_bar_chart_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("events_bar_chart"),
            },
        ),
        "events_bar_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("events_bar_chart_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_bar_chart_title"),
            }
            | (params_dict.get("events_bar_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("events_bar_chart_html_url"),
            },
        ),
        "grouped_bar_plot_widget_merge": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_bar_plot_widget_merge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("events_bar_chart_widget"),
            }
            | (params_dict.get("grouped_bar_plot_widget_merge") or {}),
            method="call",
        ),
        "events_meshgrid": Node(
            async_task=create_meshgrid.validate()
            .set_task_instance_id("events_meshgrid")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "aoi": DependsOn("events_add_temporal_index"),
                "intersecting_only": False,
            }
            | (params_dict.get("events_meshgrid") or {}),
            method="call",
        ),
        "grouped_events_feature_density": Node(
            async_task=calculate_feature_density.validate()
            .set_task_instance_id("grouped_events_feature_density")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "meshgrid": DependsOn("events_meshgrid"),
                "geometry_type": "point",
                "sum_column": DependsOn("analysis_field"),
            }
            | (params_dict.get("grouped_events_feature_density") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "drop_nan_percentiles": Node(
            async_task=drop_nan_values_by_column.validate()
            .set_task_instance_id("drop_nan_percentiles")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "density",
            }
            | (params_dict.get("drop_nan_percentiles") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events_feature_density"),
            },
        ),
        "sort_grouped_density_values": Node(
            async_task=sort_values.validate()
            .set_task_instance_id("sort_grouped_density_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "density",
                "ascending": True,
                "na_position": "last",
            }
            | (params_dict.get("sort_grouped_density_values") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("drop_nan_percentiles"),
            },
        ),
        "classify_fd": Node(
            async_task=apply_classification.validate()
            .set_task_instance_id("classify_fd")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "density",
                "output_column_name": "density_bins",
                "classification_options": {
                    "scheme": "equal_interval",
                    "k": 9,
                },
                "label_options": {
                    "label_ranges": True,
                    "label_decimals": 0,
                },
            }
            | (params_dict.get("classify_fd") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("sort_grouped_density_values"),
            },
        ),
        "grouped_fd_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("grouped_fd_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "density_bins",
                "colormap": [
                    "#5C4FE7",
                    "#269CD5",
                    "#00D0C8",
                    "#81D670",
                    "#FFD000",
                    "#F9BB12",
                    "#FF9600",
                    "#FA7306",
                    "#F23B0E",
                ],
                "output_column_name": "density_colormap",
            }
            | (params_dict.get("grouped_fd_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("classify_fd"),
            },
        ),
        "fd_rename_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("fd_rename_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "density": "Density",
                },
            }
            | (params_dict.get("fd_rename_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_fd_colormap"),
            },
        ),
        "grouped_fd_map_layer": Node(
            async_task=create_polygon_layer.validate()
            .set_task_instance_id("grouped_fd_map_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "fill_color_column": "density_colormap",
                    "get_line_width": 0,
                    "opacity": 0.4,
                },
                "legend": {
                    "label_column": "density_bins",
                    "color_column": "density_colormap",
                },
                "tooltip_columns": [
                    "Density",
                ],
            }
            | (params_dict.get("grouped_fd_map_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("fd_rename_columns"),
            },
        ),
        "grouped_fd_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("grouped_fd_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": None,
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": DependsOn("analysis_field_unit"),
                    "format_title": False,
                    "placement": "bottom-right",
                },
                "static": False,
                "max_zoom": 20,
                "widget_id": DependsOn("set_density_map_title"),
            }
            | (params_dict.get("grouped_fd_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("grouped_fd_map_layer"),
            },
        ),
        "grouped_fd_ecomap_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("grouped_fd_ecomap_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("grouped_fd_ecomap_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("grouped_fd_ecomap"),
            },
        ),
        "grouped_fd_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("grouped_fd_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_density_map_title"),
            }
            | (params_dict.get("grouped_fd_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("grouped_fd_ecomap_html_url"),
            },
        ),
        "grouped_fd_map_widget_merge": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_fd_map_widget_merge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("grouped_fd_map_widget"),
            }
            | (params_dict.get("grouped_fd_map_widget_merge") or {}),
            method="call",
        ),
        "events_table_columns": Node(
            async_task=get_column_names_from_dataframe.validate()
            .set_task_instance_id("events_table_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("column_display_order"),
                "exclude_column_names": [
                    "id",
                    "geometry",
                    "events_colormap",
                    "event_type",
                    "default_category",
                    "Event Category",
                ],
            }
            | (params_dict.get("events_table_columns") or {}),
            method="call",
        ),
        "events_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("events_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": DependsOn("events_table_columns"),
                "table_config": {
                    "enable_sorting": True,
                    "enable_filtering": False,
                    "enable_download": True,
                    "hide_header": False,
                },
                "widget_id": DependsOn("set_events_table_title"),
            }
            | (params_dict.get("events_table") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("split_event_groups"),
            },
        ),
        "table_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("table_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("table_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("events_table"),
            },
        ),
        "events_table_single_views": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("events_table_single_views")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_events_table_title"),
            }
            | (params_dict.get("events_table_single_views") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("table_html_urls"),
            },
        ),
        "grouped_table_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("events_table_single_views"),
            }
            | (params_dict.get("grouped_table_widget") or {}),
            method="call",
        ),
        "events_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("events_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("total_events_grouped_sv_widget"),
                    DependsOn("grouped_summary_table_widget"),
                    DependsOn("grouped_events_pie_widget_merge"),
                    DependsOn("grouped_events_map_widget_merge"),
                    DependsOn("grouped_bar_plot_widget_merge"),
                    DependsOn("grouped_fd_map_widget_merge"),
                    DependsOn("grouped_table_widget"),
                ],
                "groupers": DependsOn("groupers"),
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("events_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
